name: pull-request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  install_deps:
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_install_deps.yml@v3.0.0

  run_checks:
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_checks.yml@v3.0.0
    needs:
      - install_deps

  run_unit_tests:
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_unit_tests.yml@v3.0.0
    needs:
      - install_deps
