name: staging

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  install_deps:
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_install_deps.yml@v3.0.0

  run_checks:
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_checks.yml@v3.0.0
    needs:
      - install_deps

  run_unit_tests:
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_unit_tests.yml@v3.0.0
    needs:
      - install_deps

  build:
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_unit_tests.yml@v3.0.0
    needs:
      - run_checks
      - run_unit_tests

  publish:
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_publish.yml@v3.0.0
    needs:
      - build
    secrets:
      dockerhub_token: ${{ secrets.NPM_TOKEN }}
